bzindia/base/urls.py
from django.urls import path
from .views import GetPincodeView, GetLocalPlacesView

app_name = "base"

urlpatterns = [
    path('<str:latitude>/<str:longitude>/', GetPincodeView.as_view(), name="get_pincode"),
    path('get_places/<pincode>', GetLocalPlacesView.as_view(), name="get_places"),
]

bzindia/bzindia/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from django.views.static import serve
from django.urls import re_path
from django.views.static import serve

from company.feeds import (
    CompanyFeed, ContactFeed, CompanyFaqFeed, CompanyBlogFeed,
    CompanyBlogDetailFeed, CompanyAboutFeed, CompanyPrivacyPolicyFeed,
    CompanyTermsAndConditionsFeed, CompanyShippingAndDeliveryPolicyFeed,
    CompanyCancellationAndRefundPolicyFeed
    )
    
from base.feeds import (
    DetailFeed, MultipageFeed, ServiceMultipagesFeed, ProductMultipagesFeed,
    CourseMultipagesFeed, RegistrationMultipagesFeed, CompanyServicesFeed,
    CompanyProductsFeed, CompanyCoursesFeed, CompanyRegistrationsFeed,
    MetaTagFeed, HomeFeed, TestimonialFeed,
    nothing,
    )

from .sitemaps import (
    StaticViewSitemap,
    CompanySitemap,
    CompanySubPagesSitemap,
    BlogSitemap,
    MetaTagSitemap,
    CompanyDetailSitemap,
    IndiaSitemap,    
)

sitemaps = {
    'static': StaticViewSitemap,
    'companies': CompanySitemap,
    'company-subpages': CompanySubPagesSitemap,
    'blogs': BlogSitemap,
    'tags': MetaTagSitemap,
    'company-detail': CompanyDetailSitemap,
    'state-list-in-india': IndiaSitemap,    
}

urlpatterns = [
    path('django_admin/', admin.site.urls),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    # path('', include('home.urls', namespace="home")),
    path('company/', include('company.urls', namespace="company")),    

    path('admin/', include('superadmin.urls', namespace="superadmin")),
    path('authentication/', include('authentication.urls', namespace="authentication")),
    path('locations/', include('locations.urls', namespace="locations")),
    path('customer/', include('customer.urls', namespace="customer")),
    path('product/', include('product.urls', namespace="product")),
    path('directory/', include('directory.urls', namespace="directory")),
    path('service/', include('service.urls', namespace="service")),
    path('education/', include('educational.urls', namespace="education")),
    path('registration/', include('registration.urls', namespace="registration")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('base/', include('base.urls', namespace="base")),

    # api-urls
    path('company_api/', include('company_api.urls', namespace="company_api")),
    path('registration_api/', include('registration_api.urls', namespace="registration_api")),
    path('course_api/', include('course_api.urls', namespace="course_api")),
    path('service_api/', include('service_api.urls', namespace="service_api")),
    path('product_api/', include('product_api.urls', namespace="product_api")),
    path('meta_tag_api/', include('meta_tag_api.urls', namespace="meta_tag_api")),
    path('destination_api/', include('destination_api.urls', namespace="destination_api")),
    path('blog_api/', include('blog_api.urls', namespace="blog_api")),
    path('location_api/', include('location_api.urls', namespace="location_api")),
    path('home_api/', include('home_api.urls', namespace="home_api")),
    path('contact_api/', include('contact_api.urls', namespace="contact_api")),
    path('custom_pages_api/', include('custom_pages_api.urls', namespace="custom_pages_api")),
    path('meta_api/', include('meta_api.urls', namespace="meta_api")),
    path('search_api/', include('search_api.urls', namespace="search_api")),

    path('services/feed/', ServiceMultipagesFeed()),
    path('products/feed/', ProductMultipagesFeed()),
    path('courses/feed/', CourseMultipagesFeed()),
    path('registrations/feed/', RegistrationMultipagesFeed()),

    path('tag/feed/', MetaTagFeed()),
    path('tag/<str:tag_slug>/feed/', MetaTagFeed()),

    path('feed/', HomeFeed()),
    path('comments/feed/', TestimonialFeed()),

    path('<str:company_slug>/feed/', CompanyFeed()),
    path('<str:company_slug>/contact_us/feed/', ContactFeed()),
    path('<str:company_slug>/about_us/feed/', CompanyAboutFeed()),
    path('<str:company_slug>/faqs/feed/', CompanyFaqFeed()),
    path('<str:company_slug>/blog/feed/', CompanyBlogFeed()),    
    path('<str:company_slug>/blog/<str:blog_slug>/feed/', CompanyBlogDetailFeed()),    
    path('<str:type_slug>/<str:company_slug>/<str:slug>/feed/', DetailFeed()),

    path('<str:company_slug>/services/feed/', CompanyServicesFeed()),
    path('<str:company_slug>/products/feed/', CompanyProductsFeed()),
    path('<str:company_slug>/courses/feed/', CompanyCoursesFeed()),
    path('<str:company_slug>/registrations/feed/', CompanyRegistrationsFeed()),

    path('<str:company_slug>/privacy_policy/feed/', CompanyPrivacyPolicyFeed()),
    path('<str:company_slug>/terms_and_conditions/feed/', CompanyTermsAndConditionsFeed()),
    path('<str:company_slug>/shipping_and_delivery_policy/feed/', CompanyShippingAndDeliveryPolicyFeed()),    
    path('<str:company_slug>/cancellation_and_refund_policy/feed/', CompanyCancellationAndRefundPolicyFeed()),        
    

    path('<str:company_slug>/<str:slug>/feed/', ServiceMultipagesFeed()),
    path('<str:company_slug>/<str:slug>/<str:state_slug>/<str:location_slug>/feed/', MultipageFeed()),

    path('nothing/', nothing)


]

urlpatterns += [
    # ✅ Serve dynamically generated sitemaps via Django at /sitemap-django.xml
    path("sitemap-django.xml", sitemap, {"sitemaps": sitemaps}, name="django-sitemap"),

    # ✅ Serve the static sitemap index (generated by management command) at /sitemap.xml
    re_path(
        r'^sitemap\.xml$',
        serve,
        {
            'path': 'sitemaps/sitemap_index.xml',
            'document_root': os.path.join(settings.BASE_DIR, 'static'),
        },
        name='sitemap-index'
    ),

    # ✅ Serve static multipage sitemaps like /sitemap-multipage-1.xml
    re_path(
        r'^(?P<path>sitemap-multipage-\d+\.xml)$',
        serve,
        {
            'document_root': os.path.join(settings.BASE_DIR, 'static', 'sitemaps'),
        },
        name='multipage-sitemap'
    ),

    re_path(
        r'^sitemap-[a-z0-9\-]+-\d+\.xml$',
        serve,
        {
            'document_root': os.path.join(settings.BASE_DIR, 'static', 'sitemaps'),
        },
        name='location-sitemap'
    ),

    # re_path(
    #     r'^sitemap\.xml$',
    #     serve,
    #     {
    #         'path': 'sitemaps/sitemap_index.xml',
    #         'document_root': os.path.join(settings.BASE_DIR, 'static'),
    #     },
    #     name='custom-sitemap-index'
    # ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

bzindia/product/urls.py
from django.urls import path
from .views import HomeView, GetSubCategoriesView, GetProductsView, GetCategoriesView

app_name = "product"

urlpatterns = [
    path('<str:slug>', HomeView.as_view(), name="home"),

    path('get_sub_categories/', GetSubCategoriesView.as_view(), name = "get_sub_categories"),
    path('get_categories/', GetCategoriesView.as_view(), name = "get_categories"),
    path('get_products/', GetProductsView.as_view(), name = "get_products"),
]

bzindia/superadmin/urls.py
from django.urls import path
from .views import (
    HomeView, CompanyListView, AddCompanyView, UpdateCompanyView, DeleteCompanyView,
    CompanyDetailView,
    CompanyTypeListView, AddCompanyTypeView, DeleteCompanyTypeView, UpdateCompanyTypeView,    

    # Product Company

    ListProductView, AddProductView, DeleteProductView,
    ListBrandView, AddBrandView,
    ListProductCategoryView, AddProductCategoryView,
    ListProductSubCategoryView, AddProductSubCategoryView,
    ListProductColorView, AddProductColorView, UpdateProductColorView,

    AddSizeView, UpdateSizeView, ListSizeView, DeleteSizeView,

    AddProductFaqView, ListProductFaqView, UpdateProductFaqView, DeleteProductFaqView,
    AddProductReviewView, ProductReviewListView, UpdateProductReviewView, DeleteProductReviewView,

    ListProductEnquiryView, DeleteProductEnquiryView,

    AddProductDetailPageView, ProductDetailPageListView, ProductDetailPageView, UpdateProductDetailPageView, DeleteProductDetailPageView,
    DeleteProductMultiPageView,

    AddProductMultiPageView, ProductMultiPageListView, ProductMultiPageDetailView, UpdateProductMultiPageView,

    ProductBannerListView, CreateProductBannerView, UpdateProductBannerView, DeleteProductBannerView,

    # Educational Company
    AddCourseView, CourseListView, RemoveCourseView, UpdateCourseView,
    CourseProgramListView, AddCourseProgramView, RemoveCourseProgramView, UpdateCourseProgramView,
    CourseSpecializationListView, AddCourseSpecializationView, RemoveCourseSpecializationView, UpdateCourseSpecializationView,
    AddCourseDetailView, UpdateCourseDetailView, CourseDetailsListView, CourseDetailView,
    DeleteCourseDetailView,
    AddCourseFaqView, ListCourseFaqView, UpdateCourseFaqView, DeleteCourseFaqView,
    ListCourseEnquiryView, DeleteCourseEnquiryView,

    AddCourseMultiPageView, CourseMultiPageListView, CourseMultiPageDetailView, UpdateCourseMultiPageView,
    DeleteCourseMultiPageView,
    
    EducationBannerListView, CreateEducationBannerView, UpdateEducationBannerView, DeleteEducationBannerView,

    # Service Company
    ListServiceView, AddServiceView, RemoveServiceView, UpdateServiceView,
    ListServiceCategoryView, AddServiceCategoryView, RemoveServiceCategoryView, UpdateServiceCategoryView,
    ListServiceSubCategoryView, AddServiceSubCategoryView, RemoveServiceSubCategoryView, UpdateServiceSubCategoryView,
    AddServiceFaqView, ListServiceFaqView, UpdateServiceFaqView, DeleteServiceFaqView,
    ListServiceEnquiryView, DeleteServiceEnquiryView,

    AddServiceDetailView, ServiceDetailsListView, ServiceDetailView, UpdateServiceDetailView,
    DeleteServiceDetailPageView,

    AddServiceMultiPageView, ServiceMultiPageListView, ServiceMultiPageDetailView, UpdateServiceMultiPageView,
    DeleteServiceMultiPageView,

    ServiceBannerListView, CreateServiceBannerView, UpdateServiceBannerView, DeleteServiceBannerView,

    # Registration Company
    ListRegistrationView, AddRegistrationView, RemoveRegistrationView, UpdateRegistrationView,
    ListRegistrationTypeView, AddRegistrationTypeView, RemoveRegistrationTypeView, UpdateRegistrationTypeView,
    ListRegistrationSubTypeView, AddRegistrationSubTypeView, RemoveRegistrationSubTypeView, UpdateRegistrationSubTypeView,

    AddRegistrationDetailPageView, RegistrationDetailPageListView, RegistrationDetailPageView, UpdateRegistrationDetailPageView,
    DeleteRegistrationDetailPageView,

    AddRegistrationFaqView, ListRegistrationFaqView, UpdateRegistrationFaqView, DeleteRegistrationFaqView,    

    ListRegistrationEnquiryView, DeleteRegistrationEnquiryView,

    AddRegistrationMultiPageView, RegistrationMultiPageListView, RegistrationMultiPageDetailView, UpdateRegistrationMultiPageView,
    DeleteRegistrationMultiPageView,

    RegistrationBannerListView, CreateRegistrationBannerView, UpdateRegistrationBannerView, DeleteRegistrationBannerView,

    # Directory
    BaseDirectoryView,
    ListPostOfficeView, ListBankView, ListCourtView, ListPoliceStationView, ListDestinationView,

    CompanyView,

    SettingsView, UpdatePasswordView, UpdateUserDetailView,

    # Custom pages
    AddCustomPageView, AddAboutUsPageView, AddContactUsPageView, AddFaqPageView,
    AddPrivacyPolicyPageView, AddTermsAndConditionsPageView,
    BaseCustomPageView, ListAboutUsView, ListContactUsView, ListFaqView,
    ListPrivacyPolicyView, ListTermsAndConditionsView, AddShippingAndDeliveryPolicyPageView,
    ListShippingAndDeliveryPolicyView, ListCancellationAndRefundPolicyView,
    AddCancellationAndRefundPolicyPageView,

    UpdateAboutUsPageView, UpdateContactUsPageView, UpdateFaqPageView, 
    UpdatePrivacyPolicyPageView, UpdateTermsAndConditionsPageView,

    DeleteAboutUsPageView, DeleteContactUsPageView, DeleteFaqPageView,
    DeletePrivacyPolicyPageView, DeleteTermsAndConditionPageView,
    DeleteShippingAndDeliveryPolicyPageView,

    # Clients
    AddClientView, ClientListView, UpdateClientView, DeleteClientView,

    # Student Testimonials
    AddStudentTestimonialView, StudentTestimonialListView, UpdateStudentTestimonialView, DeleteStudentTestimonialView,

    # General Testimonials
    AddTestimonialView, TestimonialListView, UpdateTestimonialView, DeleteTestimonialView,

    # Blog
    AddBlogView, ListBlogView, UpdateBlogView, DeleteBlogView,
    PublishBlogView, UnPublishBlogView,

    # Meta Tag
    MetaTagListView, AddMetaTagView, UpdateMetaTagView, DeleteMetaTagView,

    # Home Content
    HomeContentView,

    # Functions
    UpdateCheckedServiceMultipageView, UpdateCheckedCourseMultipageView, 
    UpdateCheckedRegistrationMultipageView, UpdateCheckedProductMultipageView
    )

app_name = "superadmin"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),

    path('companies/', CompanyView.as_view(), name="companies"),

    # Company
    path('add_company/', AddCompanyView.as_view(), name="add_company"),
    path('update_company/<str:slug>', UpdateCompanyView.as_view(), name="update_company"),
    path('delete_company/<str:slug>', DeleteCompanyView.as_view(), name="delete_company"),
    path('companies/<str:slug>', CompanyListView.as_view(), name="filtered_companies"),

    path('company/<str:slug>', CompanyDetailView.as_view(), name="company"),

    path('add_company_type/', AddCompanyTypeView.as_view(), name="add_company_type"),
    path('update_company_type/<str:slug>', UpdateCompanyTypeView.as_view(), name="update_company_type"),
    path('company_types/', CompanyTypeListView.as_view(), name="company_types"),
    path('delete_company_type/<str:slug>', DeleteCompanyTypeView.as_view(), name="delete_company_type"),    

    # Product Company
    path('add_product/<str:slug>', AddProductView.as_view(), name="add_product"),
    path('products/<str:slug>', ListProductView.as_view(), name="products"),
    path('delete_product/<str:slug>/<str:product_slug>', DeleteProductView.as_view(), name="delete_product"),

    path('add_brand/<str:slug>', AddBrandView.as_view(), name="add_brand"),
    path('brands/<str:slug>', ListBrandView.as_view(), name="brands"),

    path('add_category/<str:slug>', AddProductCategoryView.as_view(), name="add_category"),
    path('categories/<str:slug>', ListProductCategoryView.as_view(), name="categories"),

    path('add_sub_category/<str:slug>', AddProductSubCategoryView.as_view(), name="add_sub_category"),
    path('sub_categories/<str:slug>', ListProductSubCategoryView.as_view(), name="sub_categories"),

    path('add_size/<str:slug>', AddSizeView.as_view(), name="add_size"),
    path('sizes/<str:slug>', ListSizeView.as_view(), name="sizes"),
    path('update_size/<str:slug>/<str:size_slug>', UpdateSizeView.as_view(), name="update_size"),

    path('add_color/<str:slug>', AddProductColorView.as_view(), name="add_color"),
    path('colors/<str:slug>', ListProductColorView.as_view(), name="colors"),
    path('update_color/<str:slug>/<str:color_slug>', UpdateProductColorView.as_view(), name="update_color"),

    path('add_product_faq/<str:slug>', AddProductFaqView.as_view(), name="add_product_faq"),
    path('product_faqs/<str:slug>', ListProductFaqView.as_view(), name="product_faqs"),
    path('update_product_faq/<str:slug>/<str:product_faq_slug>', UpdateProductFaqView.as_view(), name="update_product_faq"),
    path('delete_product_faq/<str:slug>/<str:product_faq_slug>', DeleteProductFaqView.as_view(), name="delete_product_faq"),

    path('add_product_reviews/<str:slug>', AddProductReviewView.as_view(), name="add_product_reviews"),
    path('product_reviews/<str:slug>', ProductReviewListView.as_view(), name="product_reviews"),
    path('update_product_review/<str:slug>/<str:product_review_slug>', UpdateProductReviewView.as_view(), name="update_product_review"),
    path('delete_product_review/<str:slug>/<str:product_review_slug>', DeleteProductReviewView.as_view(), name="delete_product_review"),

    path('product_enquiries/<str:slug>', ListProductEnquiryView.as_view(), name="product_enquiries"),
    path('delete_product_enquiry/<str:slug>/<str:enquiry_slug>/', DeleteProductEnquiryView.as_view(), name="delete_product_enquiry"),

    path('add_product_detail_page/<str:slug>', AddProductDetailPageView.as_view(), name="add_product_detail_page"),
    path('update_product_detail_page/<str:slug>/<str:product_detail_slug>', UpdateProductDetailPageView.as_view(), name="update_product_detail_page"),
    path('product_detail_pages/<str:slug>', ProductDetailPageListView.as_view(), name="product_detail_pages"),
    path('product_detail_page/<str:slug>/<str:product_detail_slug>', ProductDetailPageView.as_view(), name="product_detail_page"),
    path('delete_product_detail_page/<str:slug>/<str:detail_page_slug>', DeleteProductDetailPageView.as_view(), name="delete_product_detail_page"),

    path('add_product_multipage/<str:slug>', AddProductMultiPageView.as_view(), name="add_product_multipage"),
    path('product_multipages/<str:slug>', ProductMultiPageListView.as_view(), name="product_multipages"),

bzindia/superadmin/templates/service_company/faqs/add.html
{% extends "admin_company/base/base.html" %}
{% load static %}

{% block title %}Add {{current_company.name}} Service FAQ{% endblock title %}

{% block company_content %}  

	<!-- Content Starts -->
    <div class="row">
        <div class="col-lg-12">
            <form method="post" action="{% url 'superadmin:add_service_faq' current_company.slug %}" class="needs-validation" enctype="multipart/form-data" id="add-service-faq-form">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title mb-0" >Add Service FAQ</h4>
                    </div>
                    <div class="card-body">
                        <div class="row">                            
                            <div class="col-md-4 mb-3">
                                <label for="category-dropdown" >Category <span class="text-danger">*</span></label>
                                <select class="form-control" id="category-dropdown" name="category" required>
                                    <option value="" hidden disabled selected>Select Category</option>
                                    {% for category in categories %}
                                    <option value="{{category.slug}}">{{category.name}}</option>
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">
                                    Please provide the category.
                                </div>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>

                            <div class="col-md-4 mb-3">
                                <label for="sub-category-dropdown" >Sub Category <span class="text-danger">*</span></label>
                                <select class="form-control" id="sub-category-dropdown" name="sub_category" required>
                                    <option value="" hidden disabled selected>Select Sub Category</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please provide the sub category.
                                </div>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            <div class="col-md-4 mb-3">
                                <label for="service-dropdown" >Service <span class="text-danger">*</span></label>
                                <select class="form-control" id="service-dropdown" name="service" required>
                                    <option value="" hidden disabled selected>Select Service</option>
                                </select>
                                <div class="invalid-feedback">
                                    Please provide the service.
                                </div>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                        </div>                                                

                        <div class="form-group row">
                            <div class="col-sm-12">
                                <label class="col-form-label">Question <span class="text-danger">*</span></label>
                                <textarea class="form-control" rows="3" id="question-input" name="question" placeholder="Question"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                <label class="col-form-label">Answer <span class="text-danger">*</span></label>
                                <textarea class="form-control" rows="3" id="answer-input" name="answer" placeholder="Answer"></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 text-center">
                                <input type="checkbox" class="form-check-input" id="check-input" name="dynamic_place_rendering"></input>
                                <label for="check-input" class="form-label">Dynamic Place Rendering </label>
                            </div>
                        </div>
                    </div>
                </div>     

                <div class="text-center">
                    <button type="submit" class="btn btn-primary" id="submit-button">Submit</button>
                </div>
            </form>
                
        </div>
	<!-- /Content End -->
	
</div>
<!-- /Page Content -->
				
{% endblock company_content %}

{% block scripts %}
<script>
    $(document).ready(() => {        
        $('#category-dropdown').on('change', () => getSubCategories());
        
        $('#sub-category-dropdown').on('change', () => getServices());
    })
</script>
{% endblock scripts %}

bzindia/superadmin/templates/service_company/faqs/update.html
{% extends "admin_company/base/base.html" %}
{% load static %}

{% block title %}Update {{current_company.name}} Service FAQ{% endblock title %}

{% block company_content %}  

	<!-- Content Starts -->
    <div class="row">
        <div class="col-lg-12">
            <form method="post" action="{% url 'superadmin:update_service_faq' current_company.slug faq.slug %}" class="needs-validation" enctype="multipart/form-data" id="add-service-faq-form">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title mb-0" >Update Service FAQ</h4>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4 mb-3">
                                <label for="category-dropdown" >Category <span class="text-danger">*</span></label>
                                <select class="form-control" id="category-dropdown" name="category" required>
                                    <option value="" hidden disabled selected>Select Category</option>
                                    {% for category in categories %}
                                    <option value="{{category.slug}}" {% if faq.service.category.slug == category.slug %}selected{% endif %} >{{category.name}}</option>
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">
                                    Please provide the category.
                                </div>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>

                            <div class="col-md-4 mb-3">
                                <label for="sub-category-dropdown" >Sub Category <span class="text-danger">*</span></label>
                                <select class="form-control" id="sub-category-dropdown" name="sub_category" required>
                                    <option value="" hidden disabled selected>Select Sub Category</option>
                                    {% for sub_category in sub_categories %}
                                    <option value="{{sub_category.slug}}" {% if faq.service.sub_category.slug == sub_category.slug %}selected{% endif %} >{{sub_category.name}}</option>
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">
                                    Please provide the sub categories.
                                </div>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>

                            <div class="col-md-4 mb-3">
                                <label for="service-dropdown" >Service <span class="text-danger">*</span></label>
                                <select class="form-control" id="service-dropdown" name="service" required>
                                    <option value="" hidden disabled selected>Select Service</option>
                                    {% for service in services %}
                                    <option value="{{service.slug}}" {% if faq.service.slug == service.slug %}selected{% endif %} >{{service.name}}</option>
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">
                                    Please provide the service.
                                </div>
                                <div class="valid-feedback">
                                    Looks good!
                                </div>
                            </div>
                            
                        </div>             

                        <div class="form-group row">
                            <div class="col-sm-12">
                                <label class="col-form-label">Question <span class="text-danger">*</span></label>
                                <textarea class="form-control" rows="3" id="question-input" name="question" placeholder="Question">{% if faq.question %}{{faq.question}}{% endif %}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12">
                                <label class="col-form-label">Answer <span class="text-danger">*</span></label>
                                <textarea class="form-control" rows="3" id="answer-input" name="answer" placeholder="Answer">{% if faq.answer %}{{faq.answer}}{% endif %}</textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-12 text-center">
                                <input type="checkbox" class="form-check-input" id="check-input" name="dynamic_place_rendering" {% if faq.dynamic_place_rendering %}checked{% endif %}></input>
                                <label for="check-input" class="form-label">Dynamic Place Rendering </label>
                            </div>
                        </div>
                    </div>
                </div>     

                <div class="text-center">
                    <button type="submit" class="btn btn-primary" id="submit-button">Submit</button>
                </div>
            </form>
                
        </div>
	<!-- /Content End -->
	
</div>
<!-- /Page Content -->
				
{% endblock company_content %}

{% block scripts %}
<script>
    $(document).ready(() => {
        // Get Sub Categories
        function getSubCategories() {
            const category = $('#category-dropdown').val();
            const company = `{{current_company.slug}}`;

            $.ajax({
                type: 'GET',
                url: `{% url 'service:get_sub_categories' %}`,
                dataType: 'json',
                data: {
                    "category_slug": category,
                    "company_slug": company
                },
                success: response => {
                    $('#sub-category-dropdown').html(`<option value="" hidden disabled selected>Select Sub Category</option>`);
                    
                    if (response.sub_categories && response.sub_categories.length > 0) {
                        response.sub_categories.forEach(sub_category => {
                            $('#sub-category-dropdown').append(`<option value="${sub_category.slug}">${sub_category.name}</option>`)
                        })
                    }
                    
                    if (response.error) {
                        console.error("Error: ", response.error)
                    }
                },
                error: error => console.error("Error: ", error),
            });            
        };

        $('#category-dropdown').on('change', () => getSubCategories());

        // Get Services
        function getServices() {
            const sub_category = $('#sub-category-dropdown').val();
            const company = `{{current_company.slug}}`;

            $.ajax({
                type: 'GET',
                url: `{% url 'service:get_services' %}`,
                dataType: 'json',
                data: {
                    "sub_category_slug": sub_category,
                    "company_slug": company
                },
                success: response => {
                    $('#service-dropdown').html(`<option value="" hidden disabled selected>Select Service</option>`);
                    
                    if (response.services && response.services.length > 0) {
                        response.services.forEach(service => {
                            $('#service-dropdown').append(`<option value="${service.slug}">${service.name}</option>`)
                        })
                    }
                    
                    if (response.error) {
                        console.error("Error: ", response.error)
                    }
                },
                error: error => console.error("Error: ", error),
            });            
        };

        $('#sub-category-dropdown').on('change', () => getServices());
    })
</script>
{% endblock scripts %}