bzindia/base/urls.py
from django.urls import path
from .views import GetPincodeView, GetLocalPlacesView

app_name = "base"

urlpatterns = [
    path('<str:latitude>/<str:longitude>/', GetPincodeView.as_view(), name="get_pincode"),
    path('get_places/<pincode>', GetLocalPlacesView.as_view(), name="get_places"),
]

bzindia/bzindia/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from django.views.static import serve
from django.urls import re_path
from django.views.static import serve

from company.feeds import (
    CompanyFeed, ContactFeed, CompanyFaqFeed, CompanyBlogFeed,
    CompanyBlogDetailFeed, CompanyAboutFeed, CompanyPrivacyPolicyFeed,
    CompanyTermsAndConditionsFeed, CompanyShippingAndDeliveryPolicyFeed,
    CompanyCancellationAndRefundPolicyFeed
    )
    
from base.feeds import (
    DetailFeed, MultipageFeed, ServiceMultipagesFeed, ProductMultipagesFeed,
    CourseMultipagesFeed, RegistrationMultipagesFeed, CompanyServicesFeed,
    CompanyProductsFeed, CompanyCoursesFeed, CompanyRegistrationsFeed,
    MetaTagFeed, HomeFeed, TestimonialFeed,
    nothing,
    )

from .sitemaps import (
    StaticViewSitemap,
    CompanySitemap,
    CompanySubPagesSitemap,
    BlogSitemap,
    MetaTagSitemap,
    CompanyDetailSitemap,
    IndiaSitemap,    
)

sitemaps = {
    'static': StaticViewSitemap,
    'companies': CompanySitemap,
    'company-subpages': CompanySubPagesSitemap,
    'blogs': BlogSitemap,
    'tags': MetaTagSitemap,
    'company-detail': CompanyDetailSitemap,
    'state-list-in-india': IndiaSitemap,    
}

urlpatterns = [
    path('django_admin/', admin.site.urls),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

    # path('', include('home.urls', namespace="home")),
    path('company/', include('company.urls', namespace="company")),    

    path('admin/', include('superadmin.urls', namespace="superadmin")),
    path('authentication/', include('authentication.urls', namespace="authentication")),
    path('locations/', include('locations.urls', namespace="locations")),
    path('customer/', include('customer.urls', namespace="customer")),
    path('product/', include('product.urls', namespace="product")),
    path('directory/', include('directory.urls', namespace="directory")),
    path('service/', include('service.urls', namespace="service")),
    path('education/', include('educational.urls', namespace="education")),
    path('registration/', include('registration.urls', namespace="registration")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('base/', include('base.urls', namespace="base")),

    # api-urls
    path('company_api/', include('company_api.urls', namespace="company_api")),
    path('registration_api/', include('registration_api.urls', namespace="registration_api")),
    path('course_api/', include('course_api.urls', namespace="course_api")),
    path('service_api/', include('service_api.urls', namespace="service_api")),
    path('product_api/', include('product_api.urls', namespace="product_api")),
    path('meta_tag_api/', include('meta_tag_api.urls', namespace="meta_tag_api")),
    path('destination_api/', include('destination_api.urls', namespace="destination_api")),
    path('blog_api/', include('blog_api.urls', namespace="blog_api")),
    path('location_api/', include('location_api.urls', namespace="location_api")),
    path('home_api/', include('home_api.urls', namespace="home_api")),
    path('contact_api/', include('contact_api.urls', namespace="contact_api")),
    path('custom_pages_api/', include('custom_pages_api.urls', namespace="custom_pages_api")),
    path('meta_api/', include('meta_api.urls', namespace="meta_api")),
    path('search_api/', include('search_api.urls', namespace="search_api")),

    path('services/feed/', ServiceMultipagesFeed()),
    path('products/feed/', ProductMultipagesFeed()),
    path('courses/feed/', CourseMultipagesFeed()),
    path('registrations/feed/', RegistrationMultipagesFeed()),

    path('tag/feed/', MetaTagFeed()),
    path('tag/<str:tag_slug>/feed/', MetaTagFeed()),

    path('feed/', HomeFeed()),
    path('comments/feed/', TestimonialFeed()),

    path('<str:company_slug>/feed/', CompanyFeed()),
    path('<str:company_slug>/contact_us/feed/', ContactFeed()),
    path('<str:company_slug>/about_us/feed/', CompanyAboutFeed()),
    path('<str:company_slug>/faqs/feed/', CompanyFaqFeed()),
    path('<str:company_slug>/blog/feed/', CompanyBlogFeed()),    
    path('<str:company_slug>/blog/<str:blog_slug>/feed/', CompanyBlogDetailFeed()),    
    path('<str:type_slug>/<str:company_slug>/<str:slug>/feed/', DetailFeed()),

    path('<str:company_slug>/services/feed/', CompanyServicesFeed()),
    path('<str:company_slug>/products/feed/', CompanyProductsFeed()),
    path('<str:company_slug>/courses/feed/', CompanyCoursesFeed()),
    path('<str:company_slug>/registrations/feed/', CompanyRegistrationsFeed()),

    path('<str:company_slug>/privacy_policy/feed/', CompanyPrivacyPolicyFeed()),
    path('<str:company_slug>/terms_and_conditions/feed/', CompanyTermsAndConditionsFeed()),
    path('<str:company_slug>/shipping_and_delivery_policy/feed/', CompanyShippingAndDeliveryPolicyFeed()),    
    path('<str:company_slug>/cancellation_and_refund_policy/feed/', CompanyCancellationAndRefundPolicyFeed()),        
    

    path('<str:company_slug>/<str:slug>/feed/', ServiceMultipagesFeed()),
    path('<str:company_slug>/<str:slug>/<str:state_slug>/<str:location_slug>/feed/', MultipageFeed()),

    path('nothing/', nothing)


]

urlpatterns += [
    # ✅ Serve dynamically generated sitemaps via Django at /sitemap-django.xml
    path("sitemap-django.xml", sitemap, {"sitemaps": sitemaps}, name="django-sitemap"),

    # ✅ Serve the static sitemap index (generated by management command) at /sitemap.xml
    re_path(
        r'^sitemap\.xml$',
        serve,
        {
            'path': 'sitemaps/sitemap_index.xml',
            'document_root': os.path.join(settings.BASE_DIR, 'static'),
        },
        name='sitemap-index'
    ),

    # ✅ Serve static multipage sitemaps like /sitemap-multipage-1.xml
    re_path(
        r'^(?P<path>sitemap-multipage-\d+\.xml)$',
        serve,
        {
            'document_root': os.path.join(settings.BASE_DIR, 'static', 'sitemaps'),
        },
        name='multipage-sitemap'
    ),

    re_path(
        r'^sitemap-[a-z0-9\-]+-\d+\.xml$',
        serve,
        {
            'document_root': os.path.join(settings.BASE_DIR, 'static', 'sitemaps'),
        },
        name='location-sitemap'
    ),

    # re_path(
    #     r'^sitemap\.xml$',
    #     serve,
    #     {
    #         'path': 'sitemaps/sitemap_index.xml',
    #         'document_root': os.path.join(settings.BASE_DIR, 'static'),
    #     },
    #     name='custom-sitemap-index'
    # ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

bzindia/customer/urls.py
from django.urls import path

from .views import (CustomerHomeView, 
                    AddProductCategoryView, DeleteProductCategoryView, UpdateProductCategoryView, ListProductCategoryView,
                    AddProductSubCategoryView, ListProductSubCategoryView, UpdateProductSubCategoryView, DeleteProductSubCategoryView,
                    AddBrandView, DeleteBrandView, UpdateBrandView, ListBrandView, 
                    AddSizeView, DeleteSizeView, UpdateSizeView, ListSizeView,
                    AddColorView, DeleteColorView, UpdateColorView, ListColorView, 
                    AddProductView, DeleteProductView, UpdateProductView, ListProductView,
                    get_sub_categories_and_sizes,
                    
                    # Service Company
                    ServiceListView, DeleteServiceView, AddServiceView, UpdateServiceView,
                    AddServiceCategoryView, ListServiceCategoryView, UpdateServiceCategoryView, DeleteServiceCategoryView,
                    AddServiceSubCategoryView, ListServiceSubCategoryView, UpdateServiceSubCategoryView, DeleteServiceSubCategoryView,
                    ListServiceFaqView, AddServiceFaqView, DeleteServiceFaqView, UpdateServiceFaqView,
                    ListServiceEnquiryView, DeleteServiceEnquiryView,

                    # Registration Company
                    AddRegistrationView, ListRegistrationView, UpdateRegistrationView, DeleteRegistrationView,
                    AddRegistrationTypeView, ListRegistrationTypeView, UpdateRegistrationTypeView, DeleteRegistrationTypeView,
                    AddRegistrationSubTypeView, ListRegistrationSubTypeView, UpdateRegistrationSubTypeView, DeleteRegistrationSubTypeView,
                    AddRegistrationFaqView, ListRegistrationFaqView, UpdateRegistrationFaqView, DeleteRegistrationFaqView,
                    ListRegistrationEnquiryView, DeleteRegistrationEnquiryView,

                    # Education Company
                    CourseListView, AddCourseView, UpdateCourseView, DeleteCourseView,
                    ListCourseProgramView, ListCourseSpecializationView,
                    AddCourseFaqView, ListCourseFaqView, UpdateCourseFaqView, DeleteCourseFaqView,
                    ListCourseEnquiryView, DeleteCourseEnquiryView,
                    AddStudentTestimonialView, StudentTestimonialListView, UpdateStudentTestimonialView, DeleteStudentTestimonialView,

                    # Clients
                    AddClientView, ClientListView, UpdateClientView, DeleteClientView,

                    # General Testimonials
                    AddTestimonialView, TestimonialListView, UpdateTestimonialView, DeleteTestimonialView,
                    )

app_name = "customer"

urlpatterns = [
    path('', CustomerHomeView.as_view(), name="home"),

    # Product Company
    path('add_product_category/', AddProductCategoryView.as_view(), name="add_product_category"),
    path('product_categories/', ListProductCategoryView.as_view(), name="product_categories"),
    path('update_product_category/<str:slug>', UpdateProductCategoryView.as_view(), name="update_product_category"),
    path('delete_product_category/<str:slug>', DeleteProductCategoryView.as_view(), name="delete_product_category"),

    path('add_product_sub_category/', AddProductSubCategoryView.as_view(), name="add_product_sub_category"),
    path('product_sub_categories/', ListProductSubCategoryView.as_view(), name="product_sub_categories"),
    path('update_product_sub_category/<str:slug>', UpdateProductSubCategoryView.as_view(), name="update_product_sub_category"),
    path('delete_product_sub_category/<str:slug>', DeleteProductSubCategoryView.as_view(), name="delete_product_sub_category"),
    path('get_product_sub_categories/', get_sub_categories_and_sizes, name="get_product_sub_categories"),

    path('add_brand/', AddBrandView.as_view(), name="add_brand"),
    path('brands/', ListBrandView.as_view(), name="brands"),
    path('update_brand/<str:slug>', UpdateBrandView.as_view(), name="update_brand"),
    path('delete_brand/<str:slug>', DeleteBrandView.as_view(), name="delete_brand"),

    path('add_size/', AddSizeView.as_view(), name="add_size"),
    path('sizes/', ListSizeView.as_view(), name="sizes"),
    path('update_size/<str:slug>', UpdateSizeView.as_view(), name="update_size"),
    path('delete_size/<str:slug>', DeleteSizeView.as_view(), name="delete_size"),

    path('add_color/', AddColorView.as_view(), name="add_color"),
    path('colors/', ListColorView.as_view(), name="colors"),
    path('update_color/<str:slug>', UpdateColorView.as_view(), name="update_color"),
    path('delete_color/<str:slug>', DeleteColorView.as_view(), name="delete_color"),

    path('add_product/', AddProductView.as_view(), name="add_product"),
    path('products/', ListProductView.as_view(), name="products"),
    path('update_product/<str:slug>', UpdateProductView.as_view(), name="update_product"),
    path('delete_product/<str:slug>', DeleteProductView.as_view(), name="delete_product"),

    path('get_sub_categories_and_sizes/', get_sub_categories_and_sizes, name="get_sub_categories_and_sizes"),


    # Service Company
    path('services/', ServiceListView.as_view(), name="services"),
    path('add_services/', AddServiceView.as_view(), name="add_services"),
    path('delete_service/<str:slug>', DeleteServiceView.as_view(), name="delete_service"),
    path('update_service/<str:slug>', UpdateServiceView.as_view(), name="update_service"),

    path('service_categories/', ListServiceCategoryView.as_view(), name="service_categories"),
    path('add_service_categories/', AddServiceCategoryView.as_view(), name="add_service_categories"),
    path('delete_service_category/<str:slug>', DeleteServiceCategoryView.as_view(), name="delete_service_category"),
    path('update_service_category/<str:slug>', UpdateServiceCategoryView.as_view(), name="update_service_category"),

    path('service_sub_categories/', ListServiceSubCategoryView.as_view(), name="service_sub_categories"),
    path('add_service_sub_categories/', AddServiceSubCategoryView.as_view(), name="add_service_sub_categories"),
    path('delete_service_sub_category/<str:slug>', DeleteServiceSubCategoryView.as_view(), name="delete_service_sub_category"),
    path('update_service_sub_category/<str:slug>', UpdateServiceSubCategoryView.as_view(), name="update_service_sub_category"),

    path('service_faqs/', ListServiceFaqView.as_view(), name="service_faqs"),
    path('add_service_faqs/', AddServiceFaqView.as_view(), name="add_service_faqs"),
    path('delete_service_faq/<str:slug>', DeleteServiceFaqView.as_view(), name="delete_service_faq"),
    path('update_service_faq/<str:slug>', UpdateServiceFaqView.as_view(), name="update_service_faq"),

    path('service_enquiries/', ListServiceEnquiryView.as_view(), name="service_enquiries"),
    path('delete_service_enquiry/<str:slug>', DeleteServiceEnquiryView.as_view(), name="delete_service_enquiry"),

    # Registration Company
    path('add_registrations/', AddRegistrationView.as_view(), name="add_registrations"),
    path('registrations/', ListRegistrationView.as_view(), name="registrations"),
    path('update_registration/<str:slug>', UpdateRegistrationView.as_view(), name="update_registration"),
    path('delete_registration/<str:slug>', DeleteRegistrationView.as_view(), name="delete_registration"),

    path('add_registration_types/', AddRegistrationTypeView.as_view(), name="add_registration_types"),
    path('registration_types/', ListRegistrationTypeView.as_view(), name="registration_types"),
    path('update_registration_type/<str:slug>', UpdateRegistrationTypeView.as_view(), name="update_registration_type"),
    path('delete_registration_type/<str:slug>', DeleteRegistrationTypeView.as_view(), name="delete_registration_type"),

    path('add_registration_sub_types/', AddRegistrationSubTypeView.as_view(), name="add_registration_sub_types"),
    path('registration_sub_types/', ListRegistrationSubTypeView.as_view(), name="registration_sub_types"),
    path('update_registration_sub_type/<str:slug>', UpdateRegistrationSubTypeView.as_view(), name="update_registration_sub_type"),
    path('delete_registration_sub_type/<str:slug>', DeleteRegistrationSubTypeView.as_view(), name="delete_registration_sub_type"),

    path('add_registration_faqs/', AddRegistrationFaqView.as_view(), name="add_registration_faqs"),
    path('registration_faqs/', ListRegistrationFaqView.as_view(), name="registration_faqs"),
    path('update_registration_faq/<str:slug>', UpdateRegistrationFaqView.as_view(), name="update_registration_faq"),
    path('delete_registration_faq/<str:slug>', DeleteRegistrationFaqView.as_view(), name="delete_registration_faq"),

    path('registration_enquiries/', ListRegistrationEnquiryView.as_view(), name="registration_enquiries"),
    path('delete_registration_enquiry/<str:slug>', DeleteRegistrationEnquiryView.as_view(), name="delete_registration_enquiry"),

    # Education Company
    path('add_courses/', AddCourseView.as_view(), name="add_courses"),
    path('courses/', CourseListView.as_view(), name="courses"),
    path('update_course/<str:slug>', UpdateCourseView.as_view(), name="update_course"),
    path('delete_course/<str:slug>', DeleteCourseView.as_view(), name="delete_course"),

    path('course_programs/', ListCourseProgramView.as_view(), name="course_programs"),
    path('course_specializations/', ListCourseSpecializationView.as_view(), name="course_specializations"),

    path('add_course_faqs/', AddCourseFaqView.as_view(), name="add_course_faqs"),
    path('course_faqs/', ListCourseFaqView.as_view(), name="course_faqs"),
    path('update_course_faq/<str:slug>', UpdateCourseFaqView.as_view(), name="update_course_faq"),
    path('delete_course_faq/<str:slug>', DeleteCourseFaqView.as_view(), name="delete_course_faq"),

    path('course_enquiries/', ListCourseEnquiryView.as_view(), name="course_enquiries"),

bzindia/customer/templates/customer_education/faq/list.html
{% extends "customer_base/base.html" %}
{% load static %}

{% block title %}FAQs{% endblock title %}

{% block content %}
<!-- Page Content -->
<div class="content container-fluid">

	<div class="crms-title row bg-white">
		<div class="col">
			<h3 class="page-title m-0">
			<span class="page-title-icon bg-gradient-primary text-white me-2">
				<i class="feather-database"></i>
			</span> FAQs </h3>
		</div>
		<div class="col text-end">
			<ul class="breadcrumb bg-white float-end m-0 ps-0 pe-0">
				<li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
				<li class="breadcrumb-item active">FAQs</li>
			</ul>
		</div>
	</div>
	<!-- Page Header -->
	<div class="page-header pt-3 mb-0 ">
		<div class="row">
			<div class="col">
				<div class="dropdown">
					<a class="dropdown-toggle recently-viewed" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Recently Viewed</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="#">Recently Viewed</a>
						<a class="dropdown-item" href="#">Items I'm following</a>
						<a class="dropdown-item" href="#">All Registrations</a>
						<a class="dropdown-item" href="#">Registrations added in the last 24 hours</a>
						<a class="dropdown-item" href="#">Registrations added in the last 7 days</a>						
					</div>
				</div>
			</div>
			<div class="col text-end">
				<ul class="list-inline-item ps-0">
					<li class="nav-item dropdown list-inline-item add-lists">
						<a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
							<div class="nav-profile-text">
								<i class="fa fa-th" aria-hidden="true"></i>
							</div>
						</a>
						<div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
							<a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#add-new-list">Add New Registration</a>
						</div>
					</li>				
				</ul>
			</div>
		</div>
	</div>
	<!-- /Page Header -->	
	<div class="row">
		{% include "message.html" %}
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">									
					<h5 class="card-title">List of Course FAQs</h5>
				</div>
					<div class="card-body">
						<div class="table-responsive">
							<table class="table table-striped table-nowrap custom-table mb-0 datatable">
								<thead>
									<tr>
										<th class="checkBox">
											<label class="container-checkbox">
												<input type="checkbox">
												<span class="checkmark"></span>
											</label>
										</th>
										<th>Course Name</th>
										<th>Question</th>
										<th class="text-end">Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for faq in faqs %}
									<tr>
										<td class="checkBox">
											<label class="container-checkbox">
												<input type="checkbox">
												<span class="checkmark"></span>
											</label>
										</td>
										<td>	
											<a href="#" class="faq-obj" data-bs-toggle="modal" data-bs-target="#faq-detail-modal" data-question="{{faq.question}}" data-answer="{{faq.answer}}" data-course="{{faq.course.name}}">{{faq.course.name}}</a>
										</td>
										<td>{% if faq.question and faq.questio|length > 100 %}{{faq.question|slice:':100'}}...{% else %}{{faq.question}}{% endif %}</td>
										
										<td class="text-end">
											<div class="dropdown dropdown-action">
												<a href="#" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
												<div class="dropdown-menu dropdown-menu-right">
													<a class="dropdown-item" href="{% url 'customer:update_course_faq' faq.slug %}">Edit This FAQ</a>
													<a class="dropdown-item delete-btn" href="#" data-bs-toggle="modal" data-bs-target="#delete_company" data-name="{{faq.course.name}}" data-slug="{{faq.slug}}">Remove This FAQ</a>
												</div>
											</div>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>							
			</div>						
		</div>
	</div>
</div>
<!-- /Page Content -->
{% endblock content %}

{% block modal %}
<!-- Modal -->
<div class="modal fade" id="delete_company" tabindex="-1" role="dialog" aria-modal="true">
	<div class="modal-dialog" role="document">
		<button type="button" class="close md-close" data-bs-dismiss="modal" aria-label="Close"> </button>
		<div class="modal-content">

			<div class="modal-header">
				{% comment %} <h4 class="modal-title text-center">Delete Course</h4> {% endcomment %}
				<button type="button" class="btn-close xs-close" data-bs-dismiss="modal"></button>
			  </div>

			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<form id="deletion-form" method="post">
							{% csrf_token %}
							<h4><span class="text-danger">Deleting</span> Course FAQ. . .</h4>
							<div class="form-group row">
								<div class="col-md-12">
									<label class="col-form-label">Are you sure?</label> <br>
									<p><i>FAQ of course:</i> <span id="deleting-object"></span></p>
								</div>
							</div>							
														
							<div class="text-center d-flex justify-content-between py-3">
								<button type="submit" class="border-0 btn btn-primary btn-gradient-primary btn-rounded">Delete</button>&nbsp;&nbsp;
								<button type="button" class="btn btn-secondary btn-rounded">Cancel</button>
							</div>
						</form>
					</div>
				</div>

			</div>

		</div><!-- modal-content -->
	</div><!-- modal-dialog -->
</div><!-- modal -->

<!-- Detail Modal -->
<div class="modal right fade" id="faq-detail-modal" tabindex="-1" role="dialog" aria-modal="true">
	<div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title text-center company-name"></h4>
                <button type="button" class="btn-close xs-close" data-bs-dismiss="modal"></button>
              </div>

            <div class="modal-body">
                <div class="row" style="background: #eaeaea;">
                    <div class="col-md-12">
                        <h4 style="margin: 8px 0;">FAQ of <span id="course-name"></span></h4>
                    </div>
                </div>
                <br>                
                <div class="row">
                    <div class="col-md-12">
                        <h5 style="margin: 8px 0;">Question: </span></h5>
                        <p id="question"></p>
                    </div>                    
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h5 style="margin: 8px 0;">Answer: </span></h5>
                        <p id="answer"></p>
                    </div>                    
                </div>
                <br>
            </div>

        </div><!-- modal-content -->
    </div><!-- modal-dialog -->
</div>
<!-- Detail Modal -->
{% endblock modal %}

{% block scripts %}
<script>
	$(document).ready(() => {
		$('.delete-btn').click( function () {
			const name = $(this).data('name');
			const courseFaqSlug = $(this).data('slug');
			const companySlug = `{{company.slug}}`

			const actionUrl = `{% url 'customer:delete_course_faq' 'dummyCourseFaqSlug' %}`
			.replace('dummyCourseFaqSlug', courseFaqSlug);

			$('#deleting-object').html(name);
			$('#deletion-form').prop('action', actionUrl);
		});

        $('.faq-obj').click(function () {
            $('#question, #answer').empty();

            const course = $(this).data('course')
            const question = $(this).data('question')
            const answer = $(this).data('answer')

            if (course) {
                $('#course-name').html(course);
            }

            if (question) {
                $('#question').html(question);
            }

            if (answer) {
                $('#answer').html(answer);
            }
        });
	});
</script>
{% endblock scripts %}